### ISSUE TITLE
client_webid or client_id

### ISSUE THREAD

**Issue by matthieubosquet** [solid/authentication-panel#101]
The specification uses `client_id`, should we use `client_webid` as claim instead for consistency?

**Comment by acoburn** [comment]
We should use `client_id`, which is already a defined property in OIDC. That also aligns with the use of `client_id` in the rest of the OIDC flows.

**Comment by matthieubosquet** [comment]
Clarified with @acoburn , the `client_webid`claim I spotted is an old thing.

`client_id` is the correct claim name.
