### ISSUE TITLE
Missing vocab property oidcRegistration

### ISSUE THREAD

**Issue by matthieubosquet** [solid/authentication-panel#109]
This spec defines the property `solid:oidcRegistration`. It is currently missing from the solid vocab repository.

See: https://github.com/solid/vocab/issues/43

**Comment by acoburn** [comment]
With #165, I believe this issue can be closed

**Comment by matthieubosquet** [comment]
Sounds like it.
If I understand correctly, in the current proposal, the `solid:oidcRegistration` predicate becomes obsolete.
Is that correct?

**Comment by acoburn** [comment]
That is correct
