### ISSUE TITLE
Possibly missing `solid_oidc_supported` key in primer example

### ISSUE THREAD

**Issue by calummackervoy** [solid/authentication-panel#136]
In the [solid-oidc spec](https://solid.github.io/authentication-panel/solid-oidc/#discovery) it reads "An Identity Provider that conforms to the Solid-OIDC specification MUST advertise this in the OpenID Connect Discovery 1.0 OpenID.Discovery resource"

My assumption is that this means that the `solid_oidc_supported` key needs to be included in the resource at `.well-known/openid-configuration/`

I was a bit confused by this because in the [example configuration](https://solid.github.io/authentication-panel/solid-oidc-primer/#authorization-code-pkce-flow-step-3) from the primer it doesn't include the key, but I think it should?

**Comment by acoburn** [comment]
Thanks @calummackervoy, that's an oversight. We will fix that straight away.
