### ISSUE TITLE
lost contributions in move of HttpSig doc

### ISSUE THREAD

**Issue by bblfish** [solid/authentication-panel#143]
I would like to try the move again, as I seem to have lost all the history of improvements when I did the last commit.

**Comment by elf-pavlik** [comment]
What do you mean by 'move it again', and how did you lose all history? It was don't via PR so no one force pushed to the main branch.

**Comment by bblfish** [comment]
I probably was not careful about doing a `git mv` on the document. I can't really tell.

**Comment by bblfish** [comment]
There is actually no problem. The history is still there as seen by the [blame view](https://github.com/solid/authentication-panel/blame/main/proposals/HttpSignature.md). It is just the way github presents the icons of who has contributed that does not take it into account  (See the icons [on the top of the httpsig page](https://github.com/solid/authentication-panel/blob/main/proposals/HttpSignature.md))
