### ISSUE TITLE
keyId's do not exactly refer to keys anymore

### ISSUE THREAD

**Issue by bblfish** [solid/authentication-panel#151]
In  [Signing HTTP Messages 02](https://www.ietf.org/archive/id/draft-ietf-httpbis-message-signatures-02.html#section-5.1.2.1) the only remaining algorithm is named `hs2019` .
This algorithm actually covers nearly all the others, but shows a change in direction of the meaning of the `keyId`.
Whereas until [draft-cavage-10](https://tools.ietf.org/html/draft-cavage-http-signatures-10#section-3.1.2) the `keyId` referred to a cryptographic key, e.g. an RSA key, and the signer then had to specify the algorithm in the signature header, 

```http
Authorization: Signature keyId="rsa-key-1",algorithm="rsa-sha256",
   headers="(request-target) host date digest content-length",
   signature="Base64(RSA-SHA256(signing string))"
```

The new [Signing HTTP Messages](https://www.ietf.org/archive/id/draft-ietf-httpbis-message-signatures-02.html#section-5.1.2.1) states that

> Derived from metadata associated with keyid. Recommend support for:...

Draft-cavage-12 has the following example

```http
Signature: keyId="rsa-key-1",algorithm="hs2019",
     created=1402170695, expires=1402170995,
     headers="(request-target) (created) (expires)
       host date digest content-length",
     signature="Base64(RSA-SHA256(signing string))"
 ```

and the latest 02 IETF spec has

```http
Signature-Input: sig1=("@request-target" "host" "date"
    "cache-control" "x-empty-header" "x-example"); keyid="test-key-a";
    alg="hs2019"; created=1402170695; expires=1402170995
Signature: sig1=:K2qGT5srn2OGbOIDzQ6kYT+ruaycnDAAUpKv+ePFfD0RAxn/1BUe\
    Zx/Kdrq32DrfakQ6bPsvB9aqZqognNT6be4olHROIkeV879RrsrObury8L9SCEibe\
    oHyqU/yCjphSmEdd7WD+zrchK57quskKwRefy2iEC5S2uAH0EPyOZKWlvbKmKu5q4\
    CaB8X/I5/+HLZLGvDiezqi6/7p2Gngf5hwZ0lSdy39vyNMaaAT0tKo6nuVw0S1MVg\
    1Q7MpWYZs0soHjttq0uLIA3DIbQfLiIvK6/l0BdWTU7+2uQj7lBkQAsFZHoA96ZZg\
    FquQrXRlmYOh+Hx5D9fJkXcXe5tmAg==:
```

So essentially the type of key used and the hashing function data have been removed, and are meant to be stored with the key.

This seems to have been introduced to remove some attack vectors related I guess to the signature being replaced with a another valid one on a easier to crack hash function.

### Consequence

In the [HttpSig](https://github.com/solid/authentication-panel/blob/main/proposals/HttpSignature.md) document I have the keyId as a URL which dereferences to the following description: 

```Turtle
@prefix cert: <http://www.w3.org/ns/auth/cert#> .

<#k1>  a cert:RSAPublicKey;
     cert:modulus "00cb24ed85d64d794b..."^^xsd:hexBinary;
     cert:exponent 65537 .
```

It should I think be something closer to this:

```Turtle
@prefix cert: <http://www.w3.org/ns/auth/cert#> .

<#k1> uses [  a cert:RSAPublicKey;
         cert:modulus "00cb24ed85d64d794b..."^^xsd:hexBinary;
         cert:exponent 65537 ];
    :with Sha256 .
```     

This may mean that `did:key` no longer quite fit - if that is they only refer to keys (but let us what the did:key folks give as answer  [to my question](https://github.com/w3c-ccg/did-method-key/issues/33)).

Is there a name for such an `cryptoKey × hashingAlgo` pair?

**Comment by bblfish** [comment]
It is not clear that the problem I described above is still valid with the [April release of Signing HTTP Messages v03]( https://tools.ietf.org/html/draft-ietf-httpbis-message-signatures-03#section-2.4.2). See @jricher's mail to the [HTTP Bis WG](https://lists.w3.org/Archives/Public/ietf-http-wg/2021AprJun/0022.html).

**Comment by jricher** [comment]
@bblfish Sorry for the confusion between the versions, we (the HTTPSig editors) are tackling the biggest changes a piece at a time and that can lead to confusion like this! The changes in -03 signal the intended direction of the spec: separate specification of the key identifier and algorithm, for implementations that need to specify that. If you can get both from just the key, that's also allowed. (this is the "hs2019" style behavior)

Also, previously the algorithm and other content was not covered under the signature which lead to some possible substitution attacks, but this has all been addressed in -02 so the old motivation for deprecating all the specified algorithms has also gone away.

We welcome any additional feedback on the HTTP Sig spec to make sure that it's applicable across a wide variety of use cases like this.

**Comment by bblfish** [comment]
Ah great, to hear that. 
I understand why moving the signature to its own separate header was such an important move. 
I should be able to provide some feedback on the draft pretty soon, now that I have [implemented RFC8941](https://github.com/co-operating-systems/Reactive-SoLiD/issues/13).

**Comment by bblfish** [comment]
I think I found a bug in "Signing HTTP Messages", and reported it here: https://github.com/httpwg/http-extensions/issues/1456 
 
 But I think this issue can be closed, as the new spec allows the algorithms to be specified again.
