### ISSUE TITLE
Clarify the behaviour if/when multiple oidcRegistrations are present

### ISSUE THREAD

**Issue by csarven** [solid/authentication-panel#158]
re
>The WebID itself MUST resolve to an RDF document that MUST include a single solid:oidcRegistration property

can that be clarified to indicate whether a WebID description must only have one oidcRegistration? and related: what's the intended behaviour when more than one oidcRegistration property is present

**Comment by acoburn** [comment]
With the addition of a [JSON-LD representation of a client identifier](#165), I believe this issue can be considered resolved.

**Comment by csarven** [comment]
XXX: This is a test comment and will be deleted. Please ignore. [JSON-LD representation of a client identifier](#165)
