### ISSUE TITLE
Alternative Authentication Flow 

### ISSUE THREAD

**Issue by jaxoncreed** [solid/authentication-panel#30]
This is based on an offline discussion between @acoburn, @dmitrizagidulin, and @jaxoncreed. TLDR, it's an authentication flow that does not require token wrapping or crypto on the client. Instead, it depends on making a round trip to the OP every time the client wants to query a new RS.

The current WebID-OIDC spec uses PoP with a wrapped id_token, to a large extent because this allows the RP to scope an audience claim to a particular RS (thus addressing the issue of token exfiltration). Per OIDC, the audience claim of an ID token is the RP itself, so this mechanism allows us to direct that audience claim to a particular RS instead.

But if we are changing from using ID tokens to access tokens, we potentially have much more flexibility around the structure of those JWTs. What if, in addition to the standard ID token returned from the /token endpoint of an AS, the response contained an access token with this structure:

```
{
    "kid" : "AS key id"
}
.
{
    "sub" : "WebID of agent" ,
    "iss" : "AS/IdP identifier" ,
    "aud" : "RS/Pod identifier" ,
    "azp" : "RP/App identifier" ,
    "iat" : "..." ,
    "exp" : "..."
}
.
(AS-based-signature the above)
```

This would vastly simplify the token structure that an RS needs to validate and it eliminates the need for RPs to sign the outer envelope token. The downside is that, for each RS that a given RP interacts with, that RP would need an extra round-trip with the AS: either via the /token endpoint or some other endpoint where the RP could exchange an ID token for a signed, RS-scoped access token.

**Comment by elf-pavlik** [comment]
@jaxoncreed would you still like to pursuit this approach?

**Comment by acoburn** [comment]
The current state of the specification answers the issue raised here: https://solid.github.io/authentication-panel/solid-oidc/#resource-access-validation
