### ISSUE TITLE
SQRL authentication

### ISSUE THREAD

**Issue by bbustin** [solid/authentication-panel#36]
It may be nice to try integrating SQRL authentication. https://www.grc.com/sqrl

It is essentially a decentralized authentication scheme and *may* fit in nicely with the principles of SOLID.

**Comment by elf-pavlik** [comment]
I think this could work as one of the options some OIDC Providers could offer to their users. Each OP has full freedom with respect to what local authentication the use.
For common cases where user uses app which access resources on multiple instances of solid storage we need to handle both authentication and authorization, so we don't have just 'login' problem to solve.

**Comment by elf-pavlik** [comment]
Since we focus on OIDC based approach, SQRL might be something worth discussing on https://forum.solidproject.org/
As I mentioned in previous comment, to authenticate with OpenID Provider implementations have full freedom to implement anything they wish to support.
