### ISSUE TITLE
Validating the Access Token

### ISSUE THREAD

**Issue by elf-pavlik** [solid/authentication-panel#50]
Current draft states:
>The public key in the fingerprint of the Access Token MUST be checked against the DPoP fingerprint to ensure a match, as outlined in the DPoP Internet-Draft. To achieve this the RS must fetch the required pubic key from the IdP to match the Access Tokens cnf claim against the DPoP tokens fingerprint to verify they are a bound pair.

I think we should keep it very clear that we have two different signatures which need to be validated:
* DPoP Proof **signed by the client**
* JWT Signature on DPoP-bound access token **signed by the IdP**

Given above I don't see exactly how mentioned in current draft *public key from the IdP to match the Access Tokens cnf claim* supposed to work. cnf claim uses *client* public key not *idp* public key.

In [relevant part](https://github.com/solid/authentication-panel/blob/747a682dad58a48d8850efe8ff44b8c052621d2a/oidc-authentication.md#81-use-of-authorization-header) of @dmitrizagidulin's draft, difference between what client signs and what idp signs was captured very well.

**Comment by elf-pavlik** [comment]
Following up on what we discussed during this meeting. This section should not mention DPoP any more, all DPoP related things should go into DPoP Validation #49 

We still need to address how RS validates that claimed issuer signed the Access Token (JWT). In [OpenID Connect Core 1.0 - 10. Signatures and Encryption](https://openid.net/specs/openid-connect-core-1_0-final.html#SigEnc) we find:

> **The OP advertises its public keys via its Discovery document, or may supply this information by other means**. The RP declares its public keys via its Dynamic Registration request, or may communicate this information by other means. 

It's detailed in [OpenID Connect Discovery 1.0 - 4. Obtaining OpenID Provider Configuration Information](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig)

>  OpenID Providers supporting Discovery MUST make a JSON document available at the path formed by concatenating the string /.well-known/openid-configuration to the Issuer. The syntax and semantics of .well-known are defined in RFC 5785 [RFC5785] and apply to the Issuer value when it contains no path component. openid-configuration MUST point to a JSON document compliant with this specification and MUST be returned using the application/json content type.

With earlier section [OpenID Connect Discovery 1.0 - 3. OpenID Provider Metadata](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata) providing detailed:

> jwks_uri
> 
>REQUIRED. URL of the OP's JSON Web Key Set [JWK] document. This contains the signing key(s) the RP uses to validate signatures from the OP. The JWK Set MAY also contain the Server's encryption key(s), which are used by RPs to encrypt requests to the Server. When both signing and encryption keys are made available, a use (Key Use) parameter value is REQUIRED for all keys in the referenced JWK Set to indicate each key's intended usage. Although some algorithms allow the same key to be used for both signatures and encryption, doing so is NOT RECOMMENDED, as it is less secure. The JWK x5c parameter MAY be used to provide X.509 representations of keys provided. When used, the bare key values MUST still be present and MUST match those in the certificate. 

In Solid-OIDC RS needs to use OP's public key to verify that Access Token was signed by that OP. As I understand #58 was related to relevant section providing guidance on caching those IdP's / OP's public keys.

**Comment by EndlessTrax** [comment]
Latest commit following the most recent panel discussion - https://github.com/solid/authentication-panel/commit/87e673eee4761f65afa977fa80cdfb83268114fb

**Comment by elf-pavlik** [comment]
Once again, I would not bring up DPoP any more in this section to avoid confusion. It should only explain how RS can verify that claimed **issuer** has actually issued presented access token. Above has nothing to do with DPoP or 'cfn' claim in access token. It only deals with discovery of issuer's (OP's) signing keys and verify JWS on the access token itself. I've provided all relevant references in my previous comment.

**Comment by EndlessTrax** [comment]
We need to mention that those fingerprints need to match, though. That reader needs to know that there is a mechanism in place to check that correct DPoP proof is sent with the correct bound Access Token to the RS. If we need to move this language, I'm fine with that, but I don't think it belongs in DPoP.

As for verifying the JWS of the Access Token, that is already covered in OIDC, so should be delegated.

**Comment by elf-pavlik** [comment]
https://tools.ietf.org/html/draft-fett-oauth-dpop-04#section-7

> Resource servers MUST ensure that the fingerprint of the public key
   in the DPoP proof JWT equals the value in the "jkt" claim in the
   access token or introspection response.

For me this clearly belongs to DPoP Validation #49 section.

-----------------

> As for verifying the JWS of the Access Token, that is already covered in OIDC, so should be delegated.

To my understanding in OIDC the ID Token is signed JWT and the client uses needs to discover OP's public keys to validate the ID Token. I think we need to clearly specify the in Solid-OIDC RS should use the same mechanism of OP's public keys discovery to validate the Access Token. Once again, this doesn't involve DPoP any more and can possibly be used in case where Bearer token is used.

**Comment by elf-pavlik** [comment]
I'd like to leave this issue open. Latest draft still doesn't describe use of OIDC discovery of keys OP used to sign the DPoP-bound Access Token.

We should also keep in mind @acoburn request to only use it unless RS and OP have another way to distribute keys.
