### ISSUE TITLE
The Mechanism for the IdP to confirm app WebId ownership should be detailed

### ISSUE THREAD

**Issue by jaxoncreed** [solid/authentication-panel#54]
Currently the spec states:

    The client presents its WebID to the IdP and requests an Authorization Code.

But there is no requirement in the spec for IdPs to implement a mechanism that confirms the application's possession of that WebId. This is important because if an app can claim to be any WebId, it will mess up the access control system down the line.

**Comment by elf-pavlik** [comment]
I think this one duplicates #52

**Comment by jaxoncreed** [comment]
You are correct.
