### ISSUE TITLE
Add Detail to the "Basic Flow"

### ISSUE THREAD

**Issue by jaxoncreed** [solid/authentication-panel#55]
I know that it's only supposed to be a non-normative basic flow, but I don't think it's detailed enough to understand everything that's going on. I created a non-normative flow for an older version of the spec here https://github.com/solid/authorization-panel/blob/master/proposals/TrustedAppsReplacement.md#general-networking-flow. It would be fantastic to have that level of detail!

**Comment by EndlessTrax** [comment]
What specifically do you feel is missing from the flow that isn't already delegated to an existing spec/recommendation?

**Comment by elf-pavlik** [comment]
@jaxoncreed I think as soon as @EndlessTrax gives us a green light to make PRs you could create one with exact details you would like to include.

**Comment by acoburn** [comment]
Given the level of detail in the [Solid-OIDC primer](https://solid.github.io/authentication-panel/solid-oidc-primer/#solid-oidc-flow) can this issue be closed as resolved?

**Comment by acoburn** [comment]
This issue has been addressed with the creation of the [Solid-OIDC primer](https://solid.github.io/authentication-panel/solid-oidc-primer/#solid-oidc-flow)
