### ISSUE TITLE
Acknowledgments Section

### ISSUE THREAD

**Issue by EndlessTrax** [solid/authentication-panel#62]
Looking at various specs and the many different ways in which to write this section, this one appeals to me the most - [https://www.w3.org/TR/2019/REC-vc-data-model-20191119/#acknowledgements](https://www.w3.org/TR/2019/REC-vc-data-model-20191119/#acknowledgements). I like the straightforwardness of it. Though I'm completely open to suggestions on how we format this section. 

Can we start compiling a list of names to add?

- Dmitri Zagidulin
- Paul Worrall 
- Michael Thornburgh 
- Justin Bingham 
- Jackson Morgan 
- Aaron Coburn 
- Matthias Evering 
- Henry Story 
- Jamie Fiedler 
- Davi Ottenheimer
- Ricky White
- Adam Migus

**Comment by csarven** [comment]
+1 to using alphabetical order.

FWIW, Linked Data Notifications' Acknowledgements section: https://www.w3.org/TR/ldn/#acknowledgements links to each contributor's homepage to assist follow-up. The spec also includes `schema:contributor`s relations to each contributor's WebID (in RDFa). Hyperlinking to each contributor's WebID can be cool given Solid-OIDC's adoption as well as to make the attribution list more useful :)

It'd be great to acknowledge the following contributors:

* severin-dsr
* Ted Thibodeau Jr
* Pat McBennett
* Ruben Verborgh
* Kjetil Kjernsmo
* Michiel de Jong
* Tim Berners-Lee
* Sarven Capadisli

**Comment by csarven** [comment]
Forgot to mention: In addition to acknowledging individuals that contributed by through GitHub (creating issues, comments, commits..), meetings and chats, it'd be appropriate to acknowledge implementers who gives feedback in addition to their implementation reports. That is an external approval that advances the spec that I think should be recognised.

**Comment by csarven** [comment]
Closing with the understanding that it can be updated any time.
