### ISSUE TITLE
Define Behaviour for Multiple OpenId issuers for a WebID

### ISSUE THREAD

**Issue by jaxoncreed** [solid/authentication-panel#63]
As a reference to this issue: https://github.com/solid/node-solid-server/issues/1266

Currently, the Solid spec does not explicitly define behaviour for a user who's WebID lists multiple OpenID issuers. The normative spec should indicate that when dereferencing a WebID's issuers a server must not reject a token if any of the issuers match the issuer in the token.

**Comment by elf-pavlik** [comment]
I think wording based around "Statement matching triple `?sub <http://www.w3.org/ns/solid/terms#oidcIssuer> ?iss` covers *issued by any of user designated issuers*. For DDOS we may need to create separate issue.

**Comment by acoburn** [comment]
> I think wording based around "Statement matching triple ?sub <http://www.w3.org/ns/solid/terms#oidcIssuer> ?iss covers issued by any of user designated issuers.

As stated above, this current Solid-OIDC specification draft answers this question: https://solid.github.io/authentication-panel/solid-oidc/#resource-access-validation
