### ISSUE TITLE
Describe PKCE requirements for WebID-OIDC protocol

### ISSUE THREAD

**Issue by acoburn** [solid/authentication-panel#64]
The [current WebID-OIDC protocol definition](https://github.com/solid/webid-oidc-spec) does not mention [PKCE](https://tools.ietf.org/html/rfc7636) as a mechanism for securing authentication tokens. There are good reasons why this should be used in the interaction between a client (relying party) and identity provider (it helps to avoid replay attacks in the token request interaction).

Should this mechanism be required by the WebID-OIDC specification?

**Comment by elf-pavlik** [comment]
@acoburn please re-open if latest draft doesn't address this issue
https://github.com/solid/authentication-panel/blob/master/oidc-authentication.md
