### ISSUE TITLE
Formalize WebID-OIDC Authentication protocol

### ISSUE THREAD

**Issue by acoburn** [solid/authentication-panel#66]
There are, at present, two authentication protocols mentioned in The Solid Ecosystem (TSE) document: WebID-OIDC and WebID-TLS. The [WebID-TLS specification](https://www.w3.org/2005/Incubator/webid/spec/tls/) has already been formalized (as a draft) within W3C. The current [WebID-OIDC document](https://github.com/solid/webid-oidc-spec), however, has not been formalized into a similarly structured document with normative language.

From an implementation perspective, it would be helpful if the protocol were more precisely formalized.

**Comment by elf-pavlik** [comment]
@acoburn please re-open if latest draft doesn't address this issue
https://github.com/solid/authentication-panel/blob/master/oidc-authentication.md
