### ISSUE TITLE
Clarify requirement and use of PoP tokens in WebID-OIDC protocol

### ISSUE THREAD

**Issue by acoburn** [solid/authentication-panel#68]
The [current WebID-OIDC specification](https://github.com/solid/webid-oidc-spec#securing-tokens-for-multiple-resource-servers) describes the use of [Proof of Possession tokens](https://tools.ietf.org/html/rfc7800), but many details are left out.

1. Is the `cnf` claim required?
2. Does the `cnf` claim belong in the body or header of the JWT?
3. Does the `key` field belong in the body or header of the ID token (or access token solid/authentication-panel#65)
4. It is clear that an RS must reject a token with certain mismatched data, but must it also reject a token that doesn't contain the `cnf` claim at all? (i.e. a non-PoP token; effectively, a downgrade attack)
5. Is there a `"token_type": "pop"` claim requirement as in [the examples](https://github.com/solid/webid-oidc-spec/blob/master/application-user-workflow.md#1-wraps-id_token-in-pop_token)?
6. Should the `id_token` claim be renamed? (c.f. solid/authentication-panel#65)

Reference: https://tools.ietf.org/html/draft-fett-oauth-dpop-02

**Comment by elf-pavlik** [comment]
@acoburn does latest draft address your concerns?
https://github.com/solid/authentication-panel/blob/master/oidc-authentication.md

**Comment by acoburn** [comment]
Yes, this has been addressed
