### ISSUE TITLE
Generalize WebID-OIDC protocol beyond OIDC

### ISSUE THREAD

**Issue by acoburn** [solid/authentication-panel#69]
Some of the interactions defined in the WebID-OIDC protocol make it more similar to OAuth2 than a classic OIDC interaction. It may make sense to generalize the protocol, aligning it with OAuth2. If so, it should be decided which formalisms from OIDC would be carried over (e.g. endpoint discovery via `/.well-known/openid-configuration`)

**Comment by elf-pavlik** [comment]
@acoburn please re-open if you see need to follow up on this issuer.
