### ISSUE TITLE
How does `Basic` authentication work with app WebIds?

### ISSUE THREAD

**Issue by jaxoncreed** [solid/authentication-panel#87]
The specification defines a new way to do application authentication using an application webid (openid profile offline_access)

It also references the need for a client-secret (https://solid.github.io/authentication-panel/solid-oidc/#tokens)

This raises a few questions:
 1. For apps that have an App WebId, how are client secrets generated?
 2. Given they are somehow generated and stored on an application server, how does every IDP know what the client secret is without doing static or dynamic registration?
 3. Given client secrets cannot be stored on the browser (https://solid.github.io/authentication-panel/solid-oidc/#tokens) how would a single page application log in using an application WebId? Is that not possible by design? If so, why not allow single page applications to be represented by a WebId?
 4. Given the client had access to some secret, the encoding for a `BASIC` auth token is `{CLIENT_ID}:{CLIENT_SECRET}` (client id and client secret separated by a colon). App WebIds are URLs and, therefore contain colons. Is there any extra considerations we need to spec knowing that the `BASIC` token encoding would look like `https://app.example/webid#this:someKindOfSecret`?

**Comment by acoburn** [comment]
Why would a secret even be necessary? These are public clients.

**Comment by jaxoncreed** [comment]
If clients that depend on a client WebID are public clients, it should be referenced in the spec. Would an RS treat a client that has a client WebId different than one that does not because it's public? If so, is there any indication in the access token that it is a public client?

Also, section 6 (https://solid.github.io/authentication-panel/solid-oidc/#tokens) seems to imply that a client secret is needed to get a token. It should be specified that a client secret is not required for public webid or client webid clients.

**Comment by acoburn** [comment]
Yes, that does imply the presence of a secret. A secret _will_ likely be present for any statically-registered client, but it should be made clear that, for public clients, there will be no secret.

As for how they are treated by an RS, that will depend on the authorization system in place. There are, basically, three possibilities for what will be in the access token:

1. No `client_id` claim. This will be the case for traditional OIDC client registration (static and dynamic). An RS would treat these as anonymous client apps
2. A `client_id` equal to `solid:PublicOidcClient`. This is, effectively, the same as the first option: we have an anonymous client app
3. A `client_id` equal to a valid Client WebID document URL. This value would allow an authZ system to distinguish between anonymous apps and identifiable apps.

How an authZ system would treat these different cases is out of scope for the AuthN spec, but with this structure in place, it would allow such an authZ system to constrain access to particular resources based on client identifier. For instance, one could make a certain resource accessible to a constrained set of users and a constrained set of applications, such that user A can access the resource only with app Z or Y.

**Comment by jaxoncreed** [comment]
So, just to confirm. A client that uses a client WebId does not need to do Basic auth? Does it need an `Authorization` header at all for a `/token` request?

**Comment by acoburn** [comment]
That is correct. In this case, the client registration information will be at a public URL and therefore accessible to anyone. While one _could_ put a `client_secret` value in that registration data, a "public secret" doesn't make much sense and certainly isn't adding any security. And as such, the `Authorization` header wouldn't be necessary.

Just as a note, for ordinary OIDC clients (those with a `client_secret`), depending on how the client is registered and what the OP supports, it is also possible to send the `client_secret` as part of the JSON in the POST request. It is also possible to send a signed/encrypted JWT. IOW, the `Authorization` header at the /token endpoint is only one of several possibilities.

**Comment by jaxoncreed** [comment]
Then the main conclusion of this discussion is that the wording here should be change to not imply that a client secret is needed https://solid.github.io/authentication-panel/solid-oidc/#tokens

**Comment by acoburn** [comment]
I believe this issue has been resolved and can be closed.

**Comment by acoburn** [comment]
This issue was resolved via #92 
Please feel free to re-open if more discussion is needed
