### ISSUE TITLE
Audience claim in ID Token spec example should be app WebId

### ISSUE THREAD

**Issue by jaxoncreed** [solid/authentication-panel#88]
The audience claim for the id_token in the spec is confusing (https://solid.github.io/authentication-panel/solid-oidc/#tokens-id). 

The example says `”aud": "https://client.example.com”` But in previous examples, we established the client_id is `https://client.example.com/web#id` 

[OIDC specification 1.0](http://openid.net/specs/openid-connect-core-1_0.html) states “Audience(s) that this ID Token is intended for. It MUST contain the OAuth 2.0 client_id of the Relying Party as an audience value.” so shouldn't the `aud` for the id token be `https://client.example.com/web#id`?

**Comment by elf-pavlik** [comment]
I think you are right. Could you make PR ?

**Comment by acoburn** [comment]
That's correct: the `aud` claim in the ID token should be the client id.
